# Generated by Django 2.0.6 on 2019-06-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id_terminal', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=50)),
                ('android_id', models.CharField(max_length=50)),
                ('terminal', models.CharField(max_length=50)),
            ],
        ),
    ]
