# Generated by Django 2.2.2 on 2019-06-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='android_id',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='evento',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='android_id',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='mac',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='serie',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='terminal',
            field=models.CharField(max_length=10),
        ),
    ]
