# Generated by Django 2.2.2 on 2019-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190607_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=10)),
                ('nombre_comercio', models.CharField(max_length=50)),
                ('nro_serie', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('encargado', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('distrito', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
                ('lp', models.CharField(max_length=20)),
                ('proveedor_enlace', models.CharField(max_length=20)),
                ('funcionalidad', models.CharField(max_length=30)),
                ('ruta', models.CharField(max_length=20)),
                ('nro_contacto', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=20)),
                ('contacto_ruc', models.CharField(max_length=11)),
            ],
        ),
    ]
