# Generated by Django 2.2 on 2019-11-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_info_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_pos',
            name='terminal',
            field=models.CharField(max_length=20),
        ),
    ]
