# Generated by Django 2.2 on 2019-11-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191105_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_incidente', models.BigIntegerField()),
                ('reference', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=5)),
                ('create_time', models.DateTimeField()),
                ('assigned_party', models.CharField(max_length=12)),
                ('close_time', models.DateTimeField()),
            ],
        ),
    ]
