# Generated by Django 2.2 on 2019-11-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_incidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='num_incidente',
            field=models.BigIntegerField(null=True),
        ),
    ]
