# Generated by Django 2.2 on 2019-11-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191107_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='close_time',
            field=models.DateTimeField(null=True),
        ),
    ]
