# Generated by Django 2.2 on 2019-11-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191107_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='terminal',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
