# Generated by Django 2.2.2 on 2019-11-08 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_evento_terminal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='terminal',
        ),
    ]
