# Generated by Django 2.2.2 on 2019-11-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_terminal_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='terminal',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
