# Generated by Django 2.2 on 2019-11-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_terminal_terminal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info_pos',
            options={'verbose_name': 'Información del POS', 'verbose_name_plural': 'Información de los POS'},
        ),
        migrations.AddField(
            model_name='info_pos',
            name='estado',
            field=models.CharField(default='OLD', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info_pos',
            name='monitoreado',
            field=models.BooleanField(default=False),
        ),
    ]
