# Generated by Django 2.2 on 2019-11-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191111_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_pos',
            name='distrito',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='info_pos',
            name='nro_serie',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
