# Generated by Django 2.2 on 2019-11-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191111_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_pos',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='info_pos',
            name='nombre_comercio',
            field=models.CharField(max_length=100),
        ),
    ]
