# Generated by Django 2.2 on 2019-11-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191111_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_pos',
            name='nro_contacto',
            field=models.CharField(max_length=120),
        ),
    ]
