# Generated by Django 2.2 on 2019-11-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191111_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now_add=True)),
                ('porcentaje_de_disponibilidad', models.FloatField()),
                ('operativos', models.IntegerField()),
                ('inoperativos', models.IntegerField()),
                ('ids_intervalo_1', models.IntegerField()),
                ('ids_intervalo_2', models.IntegerField()),
                ('ids_intervalo_3', models.IntegerField()),
            ],
        ),
    ]
